apiVersion: v1
kind: Service
metadata:
  name: {{ include "httpecho.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "httpecho.name" . }}
    helm.sh/chart: {{ include "httpecho.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
    - {{ .Values.loadBalancerSourceRanges }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "httpecho.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
